version: '3'

services:
  ms-intune-entra-mcp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TENANT_ID=${TENANT_ID}
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs